services:
  frontend:
    image: localhost/vue-frontend:v1
    ports:
      - "8080:80"
    expose:
      - "8080"
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.0.254
    networks:
      demo:
        ipv4_address: 192.168.10.1
  python-api:
    image: localhost/python-api:v1
    ports:
      - "8000:8000"
    environment:
      ONTAP_HOST: "192.168.0.111"
      ONTAP_USER: "admin"
      ONTAP_PASS: "NetApp1!"
    networks:
      demo:
        ipv4_address: 192.168.10.2
    depends_on:
      - frontend
  rust-api:
    image: localhost/rust-api:v1
    ports:
      - "8080:8080"
    networks:
      demo:
        ipv4_address: 192.168.10.3
    environment:
      ONTAP_HOST: "192.168.0.111"
      ONTAP_USER: "admin"
      ONTAP_PASS: "NetApp1!"
    depends_on:
      - frontend

networks:
  demo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24