---
- name: create and configure CIFS vserver {{ cifs_svm_name }}
  ansible.builtin.include_tasks: create_and_configure_vserver.yml
  vars:
    vserver_name: "{{ cifs_svm_name }}"
    cifs_allowed: true
    nfs_allowed: false
    ip_address: "{{ cifs_svm_ip_address }}"
    subnet_mask: "{{ svm_subnet_mask }}"
    gateway: "{{ svm_gateway }}"
    home_node: "{{ cifs_svm_home_node }}"
    home_port: "{{ cifs_svm_home_port }}"
    dns_domain: "{{ svm_domain}}"
    dns_server: "{{ svm_dns_server }}"
    ad_domain: "{{ cifs_ad_domain }}"

- name: create and configure NFS vserver {{ nfs_svm_name }}
  ansible.builtin.include_tasks: create_and_configure_vserver.yml
  vars:
    vserver_name: "{{ nfs_svm_name }}"
    cifs_allowed: false
    nfs_allowed: true
    ip_address: "{{ nfs_svm_ip_address }}"
    subnet_mask: "{{ svm_subnet_mask }}"
    gateway: "{{ svm_gateway }}"
    home_node: "{{ nfs_svm_home_node }}"
    home_port: "{{ nfs_svm_home_port }}"
    dns_domain: "{{ svm_domain}}"
    dns_server: "{{ svm_dns_server }}"
